create table  student (
id 	NUMBER(3) GENERATED BY DEFAULT as IDENTITY,
name varchar(10),
age NUMBER,
sex  enum('female','male'),
PRIMARY KEY (id)
);

CREATE OR REPLACE TRIGGER mytrigger
   BEFORE INSERT ON student
   FOR EACH ROW
DECLARE
BEGIN
   :new.id := 00 || your_sequence.nextval;
END your_trigger;

create table subject (
id 	NUMBER(4) GENERATED BY DEFAULT as IDENTITY,
subject varchar(10),
teacher varchar(20),
description varchar(30),
PRIMARY KEY (id)
);

CREATE OR REPLACE TRIGGER mytrigger
   BEFORE INSERT ON student
   FOR EACH ROW
DECLARE
BEGIN
   :new.id := 100 || your_sequence.nextval;
END your_trigger;

alter table subject auto_increment= 1000;
create table score (
id 	NUMBER(4) GENERATED BY DEFAULT as IDENTITY,
student_id NUMBER(3) references student(id),
subject_id NUMBER(4) references subject(id),
score 	   DOUBLE(4),
PRIMARY KEY (id)
);


insert into student(name,age,sex) values ('zhangsan',18,'2'),('lisi',20,'1');
insert into subject(subject,teacher,description) values ('Chinese','Mr. Wang','the exam is easy'),('math','Miss Liu','the exam is difficult');
insert into score(student_id,subject_id,score) values (001,1001,80),(002,1002,60),(001,1001,70),(002,1002,60.5);

